### ISSUE TITLE
Is it possible to use MultipleTextOutputs without the key appearing in the result?

### ISSUE THREAD

**Issue by zoltanctoth** [klbostee/feathers#7]
i.e. in such a simple example

``` python
@opt("getpath", "yes")
def mapper(key, value):
    path = value[0:5]
    yield (path,None),row

if __name__ == "__main__":
    run(mapper)
```

``` sh
dumbo start example.py -input /x -output /y -hadoop /hadoop -libjar /home/zoltanctoth/env-dumbo/feathers/feathers.jar -outputformat text -numReduceTasks 0
```

Is it possible to have an output file that doesn't have its rows in a `<key>\t<value>` but simply in `<value>` format?

I tried it with `""` and `<backspace>` instead of `None` in `yield (path,None),row` but none of them seems to work.

**Comment by klbostee** [comment]
I'm afraid that's not possible no.
